[package]
name = "game_engine"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
beul = "1.0"
bytemuck = { version = "1.13", features = [ "derive" ] }
cfg-if = "1.0.0"
cgmath = "0.18.0"
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
tobj = { version = "3.2", features = [ "async" ] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
wgpu = "0.16.0"
winit = "0.28.3"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.3"
glob = "0.3"
