[workspace]
members = [
    "render",
    "world",
]

[workspace.package]
authors = ["Liam Fenneman"]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
cgmath = "0.18.0"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.17"
