[workspace]
members = [
    "render",
    "world",
    "dev-ui",
]

[workspace.package]
authors = ["Liam Fenneman"]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
cgmath = { version = "0.18.0", features = ["serde"] }
image = "0.24.6"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.17"
