[package]
name = "ge-util"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
cgmath.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
rstest = "0.17"
