[package]
name = "ge-world"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
cgmath.workspace = true
rand = "0.8.5"
rand_chacha = "0.3.1"
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
plotters = "0.3"
image = "0.24"
