[package]
name = "ge-render-vk"
authors.workspace = true
edition.workspace = true
version.workspace = true
default-run = "ge-render-vk"

[dependencies]
vulkano = "0.33.0"
vulkano-shaders = "0.33.0"
image = "0.24"
