[renderer]
target_fps = 120
wireframe_mode = false
render_distance = 2

[camera]
initial_position = [ 0.0, 15.0, 105.0 ]
initial_yaw_pitch = [ 0.0, 10.0 ]
znear_zfar = [ 0.1, 3000.0 ]
vertical_fov = 60.0
speed = 10.0
sensitivity = 0.5

[world_gen]
base_height = 100
sea_level = 100
culling = true
cull_border = false

[world_gen.noise]
octaves = 5
frequency = 0.0625
amplitude = 12.0
lacunarity = 2.0
persistence = 0.5
